name: scaler-4

on: [push]

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: usage
        run: ${{ 'echo ''The secret is ${{ secrets.SECRET }}''' }}
        run: echo "The secret is \${{ secrets.SECRET }}"
