name: scaler-4

on: [push]

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: usage
        run: ${{ 'echo ''The secret is ${{ secrets.SECRET }}''' }}
        
      - name: new
        run: echo "The secret is \${{ secrets.SECRET }}"

        
      - name: Authenticate to External API
        env:
          API_SECRET: ${{ secrets.SECRET }}
        run: |
          echo "Initiating connection..."
          echo "Authentication call completed."

      - name: Run Script with Secret
        env:
          APP_KEY: ${{ secrets.SECRET }}
        run: echo "Success"
